"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class Images {
}
Images.shallows = new Image();
Images.deepsea = new Image();
Images.lowlands = new Image();
Images.woods = new Image();
Images.hills = new Image();
Images.highlands = new Image();
Images.mountains = new Image();
Images.desert = new Image();
Images.swamp = new Image();
Images.default = new Image();
Images.troops = new Image();
Images.mounts = new Image();
Images.boats = new Image();
Images.castle = new Image();
Images.city = new Image();
Images.fortress = new Image();
Images.capital = new Image();
Images.capitalFort = new Image();
Images.wallW = new Image();
Images.wallE = new Image();
Images.wallNW = new Image();
Images.wallSW = new Image();
Images.wallNE = new Image();
Images.wallSE = new Image();
Images.harborW = new Image();
Images.harborE = new Image();
Images.harborSW = new Image();
Images.harborNW = new Image();
Images.harborSE = new Image();
Images.harborNE = new Image();
Images.bridgeW = new Image();
Images.bridgeE = new Image();
Images.bridgeSW = new Image();
Images.bridgeNW = new Image();
Images.bridgeSE = new Image();
Images.bridgeNE = new Image();
exports.Images = Images;
